// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Tool Version Limit: 2022.04
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern "C" void AESL_WRAP_dft (
volatile void* real_sample,
volatile void* imag_sample,
volatile void* real_op_0,
volatile void* real_op_1,
volatile void* real_op_2,
volatile void* real_op_3,
volatile void* real_op_4,
volatile void* real_op_5,
volatile void* real_op_6,
volatile void* real_op_7,
volatile void* real_op_8,
volatile void* real_op_9,
volatile void* real_op_10,
volatile void* real_op_11,
volatile void* real_op_12,
volatile void* real_op_13,
volatile void* real_op_14,
volatile void* real_op_15,
volatile void* real_op_16,
volatile void* real_op_17,
volatile void* real_op_18,
volatile void* real_op_19,
volatile void* real_op_20,
volatile void* imag_op_0,
volatile void* imag_op_1,
volatile void* imag_op_2,
volatile void* imag_op_3,
volatile void* imag_op_4,
volatile void* imag_op_5,
volatile void* imag_op_6,
volatile void* imag_op_7,
volatile void* imag_op_8,
volatile void* imag_op_9,
volatile void* imag_op_10,
volatile void* imag_op_11,
volatile void* imag_op_12,
volatile void* imag_op_13,
volatile void* imag_op_14,
volatile void* imag_op_15,
volatile void* imag_op_16,
volatile void* imag_op_17,
volatile void* imag_op_18,
volatile void* imag_op_19,
volatile void* imag_op_20);
